#########################
# INSTALL DOCKER
#########################
- name: Install prerequisite packages (ca-certificates and curl)
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create the keyring directory for Docker
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Add Docker's official GPG key
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

- name: Ensure the Docker GPG key is readable by all users
  # This task makes the file readable (chmod a+r) by setting mode 0644
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root

- name: Add Docker repository to APT sources 
  ansible.builtin.shell: |
    set -o pipefail
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: Update APT cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Login to docker (ansible-galaxy collection install community.docker)
  community.docker.docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"